### ISSUE TITLE
does't support arm Mac os big sur 11.2

### ISSUE THREAD

**Issue by shenyukun** [rgov/Thunderbolt3Unblocker#65] opened 2021-02-07 07:05 UTC
Last login: Sun Feb  7 14:44:09 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
shenyukundeMacbook-PRO-M1:~ wuxian$ sudo sh -c 'chown -R root:wheel /Library/Extensions/Thunderbolt3Unblocker.kext && \
> chmod -R g-w,o-w /Library/Extensions/Thunderbolt3Unblocker.kext && \
> kextcache -i / && \
> nvram -d t3u-incompatible && \
> kextload -b es.govost.ryan.Thunderbolt3Unblocker'
Password:
Executing: /usr/bin/kmutil install --volume-root / --check-rebuild
Not rebuilding KC for arch: 'arm64e'
kmutil done
Executing: /usr/bin/kmutil load -b es.govost.ryan.Thunderbolt3Unblocker
Error Domain=KMErrorDomain Code=71 "Incompatible architecture: Binary is for x86_64, but needed arch arm64e" UserInfo={NSLocalizedDescription=Incompatible architecture: Binary is for x86_64, but needed arch arm64e}
shenyukundeMacbook-PRO-M1:~ wuxian$

**Comment by rgov** [comment] 2021-02-07 14:36
Hi, this project doesn't support Apple Silicon yet.

**Comment by General13K7** [comment] 2021-02-19 17:51
Approve - i have macbook pro on m1 - need support for ARM

**Comment by General13K7** [comment] 2021-02-19 17:57
> Hi, this project doesn't support Apple Silicon yet.

Is it too hard to do M1 Support for that?

**Comment by qinyongqiang** [comment] 2021-03-05 06:48
It seems that no patch is needed in Arm Mac

**Comment by KrisCris** [comment] 2021-06-12 14:49
seems it's not working for intel based mac either?

**Comment by rgov** [comment] 2021-12-24 03:36
Dupe of #62.

**Closed by rgov** 2021-12-24 03:36 UTC
Labels: unconfirmed
