### ISSUE TITLE
Xcode build Failed

### ISSUE THREAD

**Issue by victorzuo** [rgov/Thunderbolt3Unblocker#1] opened 2018-02-08 16:40 UTC
![1518107515337](https://user-images.githubusercontent.com/6511817/35985376-7bde352a-0d31-11e8-87d4-e4ddcac92f68.jpg)

![1518107566165](https://user-images.githubusercontent.com/6511817/35985121-d366a666-0d30-11e8-8811-1a67306c09b8.jpg)

brew install libudis86 Already installed

I'm a java developer and I'm not familiar with Xcode. Please point.

**Comment by rgov** [comment] 2018-02-09 01:59
Please run `git submodule update --init --recursive` in the project directory to clone the libudis86 sources. We need to re-build libudis86 as a static library in order to link it into the kernel extension, so we cannot use the copy from Homebrew.

**Comment by victorzuo** [comment] 2018-02-09 02:51
There is another mistake
![1518144427446](https://user-images.githubusercontent.com/6511817/36009358-c3d6da12-0d86-11e8-91df-e58164f4a764.jpg)
![1518144400086](https://user-images.githubusercontent.com/6511817/36009360-c40c3126-0d86-11e8-8574-c4e815915501.jpg)

**Comment by rgov** [comment] 2018-02-09 02:52
I think this is because you're running Clean before it has actually been built. The build script there is not smart enough to handle this case.

(In the second screenshot I think you've highlighted the wrong `./configure`, it's actually the second one that's failing.)

If you just do a Build it should work.

**Comment by victorzuo** [comment] 2018-02-09 03:32
It's my compiler environment that has a problem
brew install libtool 
brew install autoconf
brew install automake
build is succeed
I hope this will solve my MacBookPro14,3 unlocking TB3
Thanks very much

**Comment by rgov** [comment] 2018-02-09 03:33
Thanks, I'll add those to the README.

**Comment by victorzuo** [comment] 2018-02-09 05:18
The latest version of Mac OS is unable to use unsigned third driver 10.12.
Close System Integrity Protection restart MacOS Command and R key terminal csrutil disable

**Comment by rgov** [comment] 2018-02-09 05:19
Does the command in the README work? Note that SIP is generally beneficial so if you can leave on as many protections as possible, you will be doing yourself a favor.

**Comment by victorzuo** [comment] 2018-02-09 05:35
It has been invalid so the current solution is to turn off

**Comment by victorzuo** [comment] 2018-02-09 06:07
System collapse 
![wechatimg64](https://user-images.githubusercontent.com/6511817/36013970-566a4330-0da2-11e8-8cfa-9063a7ffe460.jpeg)

**Comment by rgov** [comment] 2018-02-09 06:08
Aw. Do you know how to

**Comment by rgov** [comment] 2018-02-09 07:04
I've tested this on my MacBookPro14,2 (Touch Bar) and in a VMware Fusion VM, both running macOS 10.3.3. It does not panic either of them. Notably, I do not install the kext to /System/Library/Extensions, I load it after the system has booted. Please let me know more information about your setup.

**Comment by victorzuo** [comment] 2018-02-09 14:06
My mac os version 10.13.3 (17D47) MacBookPro14,3, Nvidia not use

**Comment by rgov** [comment] 2018-02-12 03:07
Please attach the panic log if you have it.

**Comment by kfiil** [comment] 2018-02-14 07:36
Hi, I have same problem with a kernel panic. Could just restart with out problems. My kernel log is here - I had to build unsigned, not sure if the is important.

[Kernel_2018-02-14-083326_Kenneths-MacBook-Pro.panic.zip](https://github.com/rgov/Thunderbolt3Unblocker/files/1723032/Kernel_2018-02-14-083326_Kenneths-MacBook-Pro.panic.zip)

**Comment by rgov** [comment] 2018-02-14 07:38
@kfiil Thanks. Same as #3.

**Comment by kfiil** [comment] 2018-02-14 07:44
Ahh sorry, did not recognise that. #3 is not solved right?

**Comment by rgov** [comment] 2018-02-14 07:48
It's not yet solved as it is not reproducible to me. I am considering swapping out Udis86 for Zydis or Capstone, in the hope that the stack corruption is caused by the disassembling. Please zip up your .kext and attach it to #3. Also please include the output of `md5 /System/Library/Kernels/kernel` and `nvram boot-args`.

**Comment by kfiil** [comment] 2018-02-14 07:57
Will do, and thanks for the effort!! We need people like when Apple is being d...s

**Comment by rgov** [comment] 2018-02-15 13:10
I believe this is a dupe of #3.

**Closed by rgov** 2018-02-15 13:10 UTC
