### ISSUE TITLE
It doesn't seem to work for me

### ISSUE THREAD

**Issue by adriantoine** [rgov/Thunderbolt3Unblocker#14] opened 2018-04-11 09:54 UTC
Hi!

I followed all the instructions and my Dell dock still doesn't work.

Here is the output of `sudo kextcache -i /`:

```
Kext with invalid signatured (-67050) allowed: <OSKext 0x7f99a1100dd0 [0x7fff9f74aaf0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
Kext with invalid signatured (-67054) allowed: <OSKext 0x7f999fdeebe0 [0x7fff9f74aaf0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
KernelCache ID: D936DC435A47451E1AFD2B550AFC04E5
Kext with invalid signatured (-67062) allowed: <OSKext 0x7fd171722950 [0x7fff9f74aaf0]> { URL = "SteamInputX.kext/ -- file:///System/Library/Extensions/", ID = "com.valvesoftware.SteamInput" }
Kext with invalid signatured (-67054) allowed: <OSKext 0x7fd1717b5f60 [0x7fff9f74aaf0]> { URL = "IOThunderboltFamily.kext/ -- file:///System/Library/Extensions/", ID = "com.apple.iokit.IOThunderboltFamily" }
Kext with invalid signatured (-67050) allowed: <OSKext 0x7fd1736da640 [0x7fff9f74aaf0]> { URL = "Thunderbolt3Unblocker.kext/ -- file:///Library/Extensions/", ID = "es.govost.ryan.Thunderbolt3Unblocker" }
```

I have installed this https://github.com/KhaosT/tb3-enabler before and it worked without any problems but it doesn't seem to be working for OSX 10.13.4 so I tried this one but it doesn't work either.

Can anyone help me?

Thanks!

**Comment by rgov** [comment] 2018-04-11 14:12
What doesn’t work? DisplayPort or HDMI? Do the USB ports work?

**Comment by adriantoine** [comment] 2018-04-11 14:29
Yeah actually the USB work, it's just the external display which is connected on HDMI that doesn't work. The dock is not "Unsupported" in System Information, so that's a bit weird, it was working with `tb3-enabler`, maybe something has changed, I'll try to reboot to see if it changes anything.

**Comment by rgov** [comment] 2018-04-12 01:17
Dupe of #11.

**Closed by rgov** 2018-04-12 01:17 UTC
