### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by baobaobuku1210** [rgov/Thunderbolt3Unblocker#13] opened 2018-04-10 17:15 UTC
DisplayPort is not work！Is there any way to do it

**Comment by rgov** [comment] 2018-04-11 00:38
Hi, please try to include some minimal information about what you are trying to do. I do not know what device you are talking about, what system you are on, etc. 

This problem is not something Thunderbolt 3 Unblocker can fix. 

Dupe of #11.

**Closed by rgov** 2018-04-11 00:38 UTC
